app:
  title: 'Prueba Técnica Nisum - API de Usuarios'
  description: 'Servicio para gestión de usuarios, prueba técnica en NISUM'
  version: '1.0.0'
  contact:
    name: 'Jonatan Felipe Soto Imio'
    email: 'cjonatansoto@gmail.com'
  security:
    jwt:
      secret: a1282cbddb64228a478d82d95c3672df4b80612c54ff521886e8f312118958cda312769c
      expirationSeconds: 86400000
spring:
  messages:
    basename: messages
    encoding: UTF-8
  application:
    name: nisum-technical-exercise
  datasource:
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    url: jdbc:h2:mem:nisumdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  h2:
    console:
      path: /h2-console
      enabled: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui
    enabled: true
    operationsSorter: method
    tagsSorter: alpha
    docExpansion: none

logging:
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate: ERROR
    com.zaxxer.hikari: ERROR
    com.nisum: DEBUG

server:
  port: 3000

